-- Create test accounts directly in auth.users table (bypassing email confirmation)
-- This script creates pre-confirmed test accounts

-- Insert test donor user
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'authenticated',
  'authenticated',
  'donor@test.com',
  '$2a$10$8K1p/a0dhrxSHxN2LOjOLOuK4/sTx/lWwRZK8r8BtYM9VcrMS6sPa', -- password: test123
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider": "email", "providers": ["email"]}',
  '{"full_name": "John Donor", "user_type": "donor"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO NOTHING;

-- Insert test NGO user
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'b2c3d4e5-f6g7-8901-bcde-f23456789012',
  'authenticated',
  'authenticated',
  'ngo@test.com',
  '$2a$10$8K1p/a0dhrxSHxN2LOjOLOuK4/sTx/lWwRZK8r8BtYM9VcrMS6sPa', -- password: test123
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider": "email", "providers": ["email"]}',
  '{"full_name": "Sarah Wilson", "user_type": "ngo", "organization_name": "Hope Foundation"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO NOTHING;

-- Create corresponding profiles for test users
INSERT INTO public.profiles (
  id,
  full_name,
  email,
  user_type,
  organization_name,
  created_at,
  updated_at
) VALUES 
(
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'John Donor',
  'donor@test.com',
  'donor',
  NULL,
  NOW(),
  NOW()
),
(
  'b2c3d4e5-f6g7-8901-bcde-f23456789012',
  'Sarah Wilson',
  'ngo@test.com',
  'ngo',
  'Hope Foundation',
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

-- Create a sample campaign for the NGO test account
INSERT INTO public.campaigns (
  id,
  title,
  description,
  goal_amount,
  current_amount,
  start_date,
  end_date,
  status,
  category,
  ngo_id,
  image_url,
  created_at,
  updated_at
) VALUES (
  'c3d4e5f6-g7h8-9012-cdef-345678901234',
  'Clean Water for Rural Communities',
  'Help us provide clean drinking water to 500 families in rural areas. Your donation will fund water purification systems and maintenance for sustainable access to clean water.',
  50000.00,
  15750.00,
  NOW() - INTERVAL '10 days',
  NOW() + INTERVAL '50 days',
  'active',
  'Health',
  'b2c3d4e5-f6g7-8901-bcde-f23456789012',
  '/placeholder.svg?height=400&width=600',
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

-- Add some sample donations
INSERT INTO public.donations (
  id,
  amount,
  donor_id,
  campaign_id,
  is_anonymous,
  payment_status,
  donor_name,
  donor_email,
  message,
  created_at
) VALUES 
(
  'd4e5f6g7-h8i9-0123-defg-456789012345',
  100.00,
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'c3d4e5f6-g7h8-9012-cdef-345678901234',
  FALSE,
  'completed',
  'John Donor',
  'donor@test.com',
  'Great cause! Happy to help.',
  NOW() - INTERVAL '5 days'
),
(
  'e5f6g7h8-i9j0-1234-efgh-567890123456',
  250.00,
  NULL,
  'c3d4e5f6-g7h8-9012-cdef-345678901234',
  TRUE,
  'completed',
  'Anonymous',
  'anonymous@donor.com',
  'Keep up the good work!',
  NOW() - INTERVAL '3 days'
) ON CONFLICT (id) DO NOTHING;
